services:
  - type: web
    name: sarpedon
    env: node
    region: frankfurt
    plan: free
    branch: develop
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
